name: ngrok_flutter_example
description: Demonstrates how to use the ngrok_flutter plugin.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8
  flutter: '>=3.3.0'

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  ngrok_flutter:
    path: ../

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  