// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: non_constant_identifier_names, unused_element, unused_field
import 'dart:ffi' as ffi;

/// Bindings for ngrok native core
class NgrokFlutterBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NgrokFlutterBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NgrokFlutterBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  ffi.Pointer<ffi.Char> ngrok_start_tunnel(
    ffi.Pointer<ffi.Char> authtoken,
    int localPort,
  ) {
    return _ngrok_start_tunnel(authtoken, localPort);
  }

  late final _ngrok_start_tunnelPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>, ffi.Int)
        >
      >('ngrok_start_tunnel');
  late final _ngrok_start_tunnel = _ngrok_start_tunnelPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>, int)>();

  void ngrok_free_string(ffi.Pointer<ffi.Char> s) {
    return _ngrok_free_string(s);
  }

  late final _ngrok_free_stringPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
        'ngrok_free_string',
      );
  late final _ngrok_free_string = _ngrok_free_stringPtr
      .asFunction<void Function(ffi.Pointer<ffi.Char>)>();
}
